FROM mcr.microsoft.com/devcontainers/python:3.13

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        # Additional library needed by some tests and accordingly by VScode Tests Discovery
        git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces

# Install Python dependencies from requirements
COPY requirements.txt ./
COPY .github/workflows/constraints.txt ./
RUN pip3 install -r requirements.txt -c constraints.txt \
    && rm -f requirements.txt constraints.txt

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
